# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jackie Keiser
tagline:          "Where Jackie tries to do everything all at once and doesn't mess it up"
description:      "Where Jackie tries to do everything all at once and doesn't mess it up"
url:              http://www.jackiekeiser.com
baseurl:          /

author:
  name:           'Jackie Keiser'
  url:            https://twitter.com/mongoosedoom

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
